// Code generated by "stringer -type=CompressionMethod"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BI_RGB-0]
	_ = x[BI_RLE8-1]
	_ = x[BI_RLE4-2]
	_ = x[BI_BITFIELDS-3]
	_ = x[BI_JPEG-4]
	_ = x[BI_PNG-5]
	_ = x[BI_ALPHABITFIELDS-6]
}

const _CompressionMethod_name = "BI_RGBBI_RLE8BI_RLE4BI_BITFIELDSBI_JPEGBI_PNGBI_ALPHABITFIELDS"

var _CompressionMethod_index = [...]uint8{0, 6, 13, 20, 32, 39, 45, 62}

func (i CompressionMethod) String() string {
	if i < 0 || i >= CompressionMethod(len(_CompressionMethod_index)-1) {
		return "CompressionMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompressionMethod_name[_CompressionMethod_index[i]:_CompressionMethod_index[i+1]]
}
