// Code generated by "stringer -type=InternetProtocol"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HOPOPT-0]
	_ = x[ICMP-1]
	_ = x[IGMP-2]
	_ = x[GGP-3]
	_ = x[IPinIP-4]
	_ = x[ST-5]
	_ = x[TCP-6]
}

const _InternetProtocol_name = "HOPOPTICMPIGMPGGPIPinIPSTTCP"

var _InternetProtocol_index = [...]uint8{0, 6, 10, 14, 17, 23, 25, 28}

func (i InternetProtocol) String() string {
	if i < 0 || i >= InternetProtocol(len(_InternetProtocol_index)-1) {
		return "InternetProtocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InternetProtocol_name[_InternetProtocol_index[i]:_InternetProtocol_index[i+1]]
}
